In [1]:
import sys
import numpy as np
import matplotlib

In [3]:
print("Python ", sys.version)
print("numpy ", np.__version__)
print("matplotlib ", matplotlib.__version__)

Python  3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
numpy  1.18.5
matplotlib  3.2.2


In [4]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# output of current layer
layer_outputs = []

for neuron_weights, neuron_biases in zip(weights, biases):
  # output of current neuron
  neuron_output = 0
  for n_input, weight in zip(inputs, neuron_weights):
    neuron_output += n_input*weight
  neuron_output += neuron_biases
  layer_outputs.append(neuron_output)

print(layer_outputs)
     

[4.8, 1.21, 2.385]


In [5]:
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [6]:
X = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.13935838 -0.31107463  0.01408597  0.37844053  0.30255397]
 [ 0.36050967  0.52800636  0.45239701 -0.28063869  0.06632691]
 [ 0.32032984  0.2121394   0.2995974   0.84148622  0.93148376]]
[[-0.03032597 -0.08641041]
 [ 0.03560587  0.05011712]
 [ 0.00046333 -0.11709278]]
